###

// TEST FOR EXERCISE (4.15)
POST http://localhost:3001/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "AAA",
  "name": "aaa",
  "password": "fullstack"
}

###

// TEST FOR EXERCISE (4.15)
GET http://localhost:3001/api/users
Accept: application/json

###

POST http://localhost:3001/api/login
Accept: application/json
Content-Type: application/json

{
  "username": "AAA",
  "password": "fullstack"
}

###